### ISSUE TITLE
在输入框为空的时候考虑禁掉生成按钮？

### ISSUE THREAD

**Issue by lethal233** [kingcos/JueJueZiGenerator#2]
这个undefined也太秀了
![image](https://user-images.githubusercontent.com/47763046/130203165-21ad17ca-b2c3-417f-bb4c-5ef42d898e94.png)

**Comment by lethal233** [comment]
或者考虑一下把中间的条件判断句改一改？如果判定传参进去的something为空字符串，则`verb == noun == ""` 即可？

**Comment by kingcos** [comment]
抱歉，刚开始看 Issue。

感谢你的反馈，这块其实我在自测阶段已经发现了这个小问题，但因偶然出现的 `undefined` 多了点程序员的小乐趣，所以并没有去兼容 😂

**Comment by lethal233** [comment]
> 抱歉，刚开始看 Issue。
> 
> 感谢你的反馈，这块其实我在自测阶段已经发现了这个小问题，但因偶然出现的 `undefined` 多了点程序员的小乐趣，所以并没有去兼容 😂

哈哈哈行，那可以关闭该issue了
