### ISSUE TITLE
java男是什么梗？？

### ISSUE THREAD

**Issue by petrel2015** [kingcos/JueJueZiGenerator#3]

**Comment by akFace** [comment]
在集美们中是程序员的意思

**Comment by chouchun-ljz** [comment]
气到跺jiojio，为什么不是py男

**Comment by Him392** [comment]
气抖冷，为什么不是C艹男（

**Comment by kingcos** [comment]
Sorry，刚开始看 Issue。

我来解释下，最初看到 Java 男是在群中有人发类似的梗，所以就加上了，没有任何歧视哈～我个人在大学也学习和写了近四年 Java，也算是个 Java 男了。如果有骂名，我来背！😂

**Comment by akFace** [comment]
> 气到跺jiojio，为什么不是py男

世界上最好的语言是Java（滑稽
