### ISSUE TITLE
输入框可以拆分成两个独立的 input，各代表动词名词

### ISSUE THREAD

**Issue by buptsb** [kingcos/JueJueZiGenerator#6]
独立的 input 更容易引导用户进行输入，可以用 placeholder 进行动/名词提示，避免出现 undefined 的情况。

或者直接上 TensorFlow.js 进行分词。

**Comment by kingcos** [comment]
抱歉～刚刚看到这个 Issue 已经关闭了～

独立的 Input 其实之前也有考虑过，不过虽然更加清晰但增加了用户多次点击，所以放弃了这个想法；
另外 `undefined` 也有点小彩蛋的意味做了保留；
TensorFlow.js 确实更加专业和可用，但我这方面确实了解不多，如果以后有机会学习可以考虑～

最后再次感谢提出 Issue～
